
import random
import string
import hashlib



print("Welcome to this password generator.")


def character():
    length = int(input('\nEnter the length of password: '))
    lower = string.ascii_lowercase
    upper = string.ascii_uppercase
    num = string.digits
    symbols = string.punctuation
    all = string.ascii_letters + string.digits + string.punctuation
    temp = random.sample(all,length)
    password = "".join(temp)
    pass_var = "".join(random.sample(all,length))
    hashed_password = hashlib.md5(pass_var.encode()).hexdigest()
    ENCRYPT = input("Do you want to encrypt the password generated by hashing? yes/no? Please note that by encrypting, the password length is indefinite. ")
    if "yes" in ENCRYPT:
        print(f"Encrypted password is: {hashed_password}")
    elif "no" in ENCRYPT:
        print(f"This is your password: {password}")
character()


